# Generated by Django 4.2.3 on 2023-08-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_temporada'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='fechaFin',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='temporada',
            name='fechaInicio',
            field=models.DateField(default=None),
        ),
    ]
