# Generated by Django 4.2.3 on 2023-08-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_temporada_fechafin_temporada_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
