# Generated by Django 4.2.3 on 2023-08-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_temporada_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.competencia'),
        ),
    ]
