# Generated by Django 4.2.3 on 2023-08-03 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_temporada_competencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoModalidad', models.CharField(max_length=50)),
                ('temporada', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.temporada')),
            ],
        ),
    ]
