# Generated by Django 4.2.3 on 2023-08-03 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_modalidad_temporada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidad',
            name='temporada',
        ),
        migrations.AddField(
            model_name='temporada',
            name='modalidad',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.modalidad'),
        ),
    ]
