# Generated by Django 4.2.3 on 2023-08-03 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_modalidad_temporada_temporada_modalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('esPorEquipos', models.BooleanField(default=False)),
                ('esPorPuntos', models.BooleanField(default=False)),
                ('cantidadJugadores', models.IntegerField(default=0)),
                ('puntosLimite', models.IntegerField(default=0)),
                ('duracionPartido', models.IntegerField(default=0)),
                ('cantidadEquipos', models.IntegerField(default=0)),
                ('cantidadTiempos', models.IntegerField(default=0)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.temporada')),
            ],
        ),
    ]
