# Generated by Django 4.2.3 on 2023-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='cantidadEquipos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='cantidadJugadores',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='duracionPartido',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='esPorEquipos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='esPorPuntos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='puntosLimite',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
