# Generated by Django 4.2.3 on 2023-08-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_competidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('numCanchas', models.IntegerField(verbose_name='Numero de canchas')),
            ],
        ),
        migrations.RemoveField(
            model_name='competidor',
            name='deporte',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFecha', models.IntegerField(null=True, verbose_name='Numero de fecha')),
                ('cancha', models.IntegerField(blank=True, null=True, verbose_name='Numero de cancha')),
                ('Grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.grupo')),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_locales', to='myapp.equipo')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitantes', to='myapp.equipo')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.horario')),
            ],
        ),
    ]
