# Generated by Django 4.2.3 on 2023-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_horario_remove_competidor_deporte_alter_grupo_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='horaFin',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='horario',
            name='horaInicio',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de inicio'),
        ),
    ]
