# Generated by Django 4.2.3 on 2023-08-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_horario_horafin_horario_horainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='horario',
            name='deporte',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.deporte'),
        ),
    ]
