# Generated by Django 4.2.3 on 2023-08-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_grupo_deporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='deporte',
        ),
    ]
