# Generated by Django 4.2.3 on 2023-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_grupo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora'),
        ),
    ]
