# Generated by Django 4.2.3 on 2023-08-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='modalidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.modalidad'),
        ),
    ]
