# Generated by Django 4.2.3 on 2023-08-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_competidor_password_alter_competidor_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competidor',
            options={},
        ),
        migrations.AlterModelTable(
            name='competidor',
            table='competidor',
        ),
    ]
