# Generated by Django 4.2.3 on 2023-08-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_partido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='numFecha',
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha'),
        ),
    ]
