# Generated by Django 4.2.3 on 2023-08-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_partido_numfecha_partido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='marcador_local',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marcador local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='marcador_visitante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marcador visitante'),
        ),
    ]
