# Generated by Django 4.2.3 on 2023-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_partido_marcador_local_partido_marcador_visitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='marcador_local',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Marcador local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='marcador_visitante',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Marcador visitante'),
        ),
    ]
