# Generated by Django 4.2.3 on 2023-08-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_partido_marcador_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='marcador_local',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Marcador local'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='marcador_visitante',
            field=models.IntegerField(blank=True, default='0', null=True, verbose_name='Marcador visitante'),
        ),
    ]
