# Generated by Django 4.2.3 on 2023-08-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_partido_marcador_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('En juego', 'En juego'), ('finalizado', 'Finalizado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
