# Generated by Django 4.2.3 on 2023-08-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_partido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('EN JUEGO', 'En juego'), ('FINALIZADO', 'Finalizado'), ('PENDIENTE', 'Pendiente'), ('CANCELADO', 'descnaso'), ('DESCANSO', 'descanso'), ('APLAZADO', 'aplazado'), ('PAUSADO', 'pausado')], default='pendiente', max_length=20),
        ),
    ]
