# Generated by Django 4.2.3 on 2023-08-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Estadistica',
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidosEmpatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidosGanados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidosJugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidosPerdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
    ]
